version: '3.8'

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://order_user:order_password@order-db:5432/order_db
      - SECRET_KEY=your-secret-key-here
      - INVENTORY_SERVICE_URL=http://inventory-service:5001
      - FLASK_ENV=development
    depends_on:
      - order-db
    networks:
      - warehouse-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  order-db:
    image: postgres:15-alpine
    container_name: order-db
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_password
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - warehouse-network
    restart: unless-stopped

volumes:
  order_db_data:

networks:
  warehouse-network:
    external: true